Repository Meowhere/Meowhere, pull requests merged in 2025-06, with the labels that each got.

#136 [Feat] 모바일 ui 구현
  src/app/profile/components/.gitkeep
  src/app/profile/favorites/components/.gitkeep
  src/app/profile/favorites/page.tsx
  src/app/profile/my-activities/components/.gitkeep
  src/app/profile/my-activities/page.tsx
  src/app/profile/my-info/page.tsx
  src/app/profile/my-reservations/page.tsx
  src/app/profile/notifications/components/.gitkeep
  src/app/profile/notifications/page.tsx
  src/app/profile/page.tsx
  src/app/profile/reservations/components/.gitkeep
  src/app/profile/reservations/edit/[id]/page.tsx
  src/app/profile/reservations/page.tsx
  src/components/layout/navbar/BNB.tsx
  src/types/input.types.ts
Labels: 🐛버그 수정 (Bug), ✨기능 추가 (Feature), 🔧 설정 변경 (Chore)

#149 [Feat] fetchFromClient, fetchFromServer 함수 추가
  src/app/api/auth/tokens/route.ts
  src/app/test/route/activities/CreateActivityTest.tsx
  src/app/test/route/activities/page.tsx
  src/app/test/route/my-activities/page.tsx
  src/lib/fetch/fetchFromClient.ts
  src/lib/fetch/fetchFromServer.ts
  src/lib/fetchWithAuth.ts
  src/utils/token-refresh.ts
Labels: ✨기능 추가 (Feature), 🔨 리팩토링 (Refactor)

#147 [Feat] 예약 내역 반응형 UI 및 드롭다운 트리거 UI 추가
  src/app/my-page/reservations/components/ReservationsCard.tsx
  src/app/my-page/reservations/page.tsx
  src/app/profile/reservations/components/.gitkeep
  src/app/profile/reservations/components/ReservationsCard.tsx
  src/app/profile/reservations/components/ReservationsLabel.tsx
  src/app/profile/reservations/edit/[id]/page.tsx
  src/app/profile/reservations/page.tsx
  src/components/common/dropdowns/dropdown-item/DropdownItem.tsx
  src/components/common/dropdowns/dropdown-menu/DropdownMenu.tsx
Labels: ✨기능 추가 (Feature), 🔧 설정 변경 (Chore)

#156 [Feat] 체험 상세 페이지 UI 구현 임시
  package-lock.json
  package.json
  public/assets/icons/test/img-main.jpg
  public/assets/icons/test/img-sub1.jpg
  public/assets/icons/test/img-sub2.jpg
  public/assets/icons/test/img-sub3.jpg
  public/assets/icons/test/user1.jpg
  public/assets/icons/test/user2.jpg
  public/assets/icons/test/user3.jpg
  public/assets/icons/test/user4.jpg
  public/assets/icons/test/user5.jpg
  public/assets/icons/test/user6.jpg
  src/app/activities/[id]/components/.gitkeep
  src/app/activities/[id]/components/common/Divider.tsx
  src/app/activities/[id]/components/common/OverlayContent.tsx
  src/app/activities/[id]/components/common/SectionTItle.tsx
  src/app/activities/[id]/components/common/VerticleDIvider.tsx
  src/app/activities/[id]/components/experience/ExperienceDescription.tsx
  src/app/activities/[id]/components/experience/ExperienceImageViewer.tsx
  src/app/activities/[id]/components/experience/ExperienceLocationMap.tsx
  src/app/activities/[id]/components/experience/ExperienceSummarySection.tsx
  src/app/activities/[id]/components/reservation/ReservationBox.tsx
  src/app/activities/[id]/components/reservation/ReservationMobileFooter.tsx
  src/app/activities/[id]/components/review/ReviewCard.tsx
  src/app/activities/[id]/components/review/ReviewSection.tsx
  src/app/activities/[id]/components/review/ReviewSummary.tsx
  src/app/activities/[id]/page.tsx
  src/constants/api.ts
  src/lib/formatRelativeTime.ts
  src/types/global.d.ts
  src/types/kakao-map.types.ts
  src/types/reservation.types.ts
  src/types/review.type.ts
  src/utils/getSatisfactionLabel.ts
  tailwind.config.js
Labels: ✨기능 추가 (Feature)

#158 [Feat] 모바일 체험 검색 및 필터
  src/app/client-layout.tsx
  src/app/page.tsx
  src/components/layout/Footer.tsx
  src/components/layout/navbar/Navbar.tsx
  src/components/layout/navbar/components/Category.tsx
  src/components/layout/navbar/components/CategoryButton.tsx
  src/components/layout/navbar/components/CategorySection.tsx
  src/components/layout/navbar/components/FilterSection.tsx
  src/components/layout/navbar/components/MainPageGNB.tsx
  src/components/layout/navbar/components/PlaceFilter.tsx
  src/components/layout/navbar/components/PriceFilter.tsx
  src/components/layout/navbar/components/SearchButton.tsx
  src/components/layout/navbar/components/SearchFilters.tsx
  src/components/layout/navbar/components/SubPageGNB.tsx
  src/components/layout/navbar/components/UserMenu.tsx
  src/components/layout/navbar/index.tsx
  src/components/layout/navbar/mobile/BNB.tsx
  src/hooks/useDebouncedValue.ts
  src/hooks/useGnb.ts
  src/hooks/useURLQuery.ts
  src/store/gnbStore.ts
  src/store/uiStore.ts
  src/styles/globals.css
  src/types/activity.types.ts
Labels: ✨기능 추가 (Feature), 🔨 리팩토링 (Refactor)

#164 [Feat] 체험 등록 UI 구현
  public/assets/icons/ico-plus.svg
  src/app/profile/my-activities/components/NotFoundActivities.tsx
  src/app/profile/my-activities/components/activity-management/ManagementCards.tsx
  src/app/profile/my-activities/page.tsx
  src/app/profile/my-activities/register/components/Category.tsx
  src/app/profile/my-activities/register/components/RegisterForm.tsx
  src/app/profile/my-activities/register/components/UploadImg.tsx
  src/app/profile/my-activities/register/components/UploadImgList.tsx
  src/app/profile/my-activities/register/components/register-calendar/RegisterCalendar.tsx
  src/app/profile/my-activities/register/components/register-calendar/RegisterCalendarItem.tsx
  src/app/profile/my-activities/register/page.tsx
Labels: ✨기능 추가 (Feature)

#159 [Fix] input& textarea 컴포넌트 수정
  package-lock.json
  package.json
  src/app/test/input/page.tsx
  src/components/common/inputs/Input.tsx
  src/components/common/inputs/Textarea.tsx
  src/types/input.types.ts
Labels: 🐛버그 수정 (Bug), 💄 스타일 (Style), 🔨 리팩토링 (Refactor)

#170 [Feat] 체험 등록 목록 무한 스크롤 구현
  package-lock.json
  package.json
  src/app/profile/my-activities/components/skeleton-ui/SkeletonActivities.tsx
  src/app/profile/my-activities/components/skeleton-ui/SkeletonActivitiesList.tsx
  src/app/profile/my-activities/page.tsx
  src/hooks/useInfiniteActivities.ts
  src/types/my-activities.types.ts
Labels: ✨기능 추가 (Feature)

#175 [Feat] 예약 현황 드롭다운 추가 및 UI 구현 완료
  package-lock.json
  src/app/profile/my-reservations/components/MyReservationsModalCard.tsx
  src/app/profile/my-reservations/components/ReservationCalendar.tsx
  src/app/profile/my-reservations/page.tsx
  src/app/profile/reservations/page.tsx
  src/components/common/modals/ReservationModal.tsx
  src/constants/reservation-modal.ts
  src/hooks/useReservationModal.tsx
  src/hooks/useReservationsByTime.tsx
  src/hooks/useReservedSchedules.tsx
  src/hooks/useUpdateReservation.tsx
  src/types/reservation-modal.types.ts
  src/utils/date-format.ts
Labels: ✨기능 추가 (Feature), 💄 스타일 (Style)

#178 [Fix] Dropdown 에러사항 해결(트리거 여부, 트리거 text 잘림, etc)
  src/app/profile/my-reservations/components/ReservationCalendar.tsx
  src/app/profile/my-reservations/page.tsx
  src/components/common/dropdowns/Dropdown.tsx
  src/components/common/dropdowns/DropdownMenu.tsx
  src/components/common/dropdowns/DropdownTrigger.tsx
  src/components/common/modals/ReservationModal.tsx
  src/types/dropdown-menu.types.ts
  src/types/dropdown.types.ts
Labels: 🐛버그 수정 (Bug)

#181 [Feat] 리뷰 등록 및 예약 취소 API 연결
  src/app/profile/reservations/components/ReservationsCard.tsx
  src/app/profile/reservations/page.tsx
  src/components/common/modals/CreateReviewModal.tsx
  src/hooks/useCancelReservation.ts
  src/hooks/useMyReservations.ts
  src/hooks/usePostReview.ts
  src/hooks/useReservationModal.ts
  src/hooks/useReservationsByTime.ts
  src/hooks/useReservedSchedules.ts
  src/hooks/useUpdateReservation.ts
  src/types/modal.types.ts
Labels: ✨기능 추가 (Feature), 🔨 리팩토링 (Refactor)

#180 [Feat] 데스크톱 GNB 및 필터기능
  package-lock.json
  public/assets/icons/logo/ico-image-loading.svg
  public/assets/icons/logo/ico-logo-small.svg
  src/app/_components/ActivityCard.tsx
  src/app/_components/PopularActivitiesBanner.tsx
  src/app/page.tsx
  src/components/layout/navbar/components/CategorySection.tsx
  src/components/layout/navbar/components/FilterSection.tsx
  src/components/layout/navbar/components/MainPageGNB.tsx
  src/components/layout/navbar/components/PlaceFilter.tsx
  src/components/layout/navbar/components/PriceFilter.tsx
  src/components/layout/navbar/components/SearchFilters.tsx
  src/components/layout/navbar/desktop/DesktopCategorySection.tsx
  src/components/layout/navbar/desktop/DesktopFilterSection.tsx
  src/components/layout/navbar/desktop/DesktopGNB.tsx
  src/components/layout/navbar/desktop/DesktopSearchFilters.tsx
  src/components/layout/navbar/index.tsx
  src/components/layout/navbar/mobile/MobileSearchFilters.tsx
  src/hooks/useSearchFilters.ts
Labels: ✨기능 추가 (Feature), 💄 스타일 (Style)

#183 [Feat] date time picker & sort & postAddress 적용
  public/assets/icons/ico-filter.svg
  public/assets/icons/ico-filtered.svg
  src/app/profile/components/ProfileMenuItem.tsx
  src/app/profile/components/Sidebar.tsx
  src/app/profile/layout.tsx
  src/app/profile/my-activities/register/components/Category.tsx
  src/app/profile/my-activities/register/components/PostAddress.tsx
  src/app/profile/my-activities/register/components/RegisterForm.tsx
  src/app/profile/my-activities/register/components/Sort.tsx
  src/app/profile/my-activities/register/components/register-calendar/DateTimePicker.tsx
  src/app/profile/my-activities/register/components/register-calendar/RegisterCalendar.tsx
  src/app/profile/my-activities/register/components/register-calendar/RegisterCalendarItem.tsx
  src/app/profile/page.tsx
  src/components/common/icons/SortIcon.tsx
  src/types/my-activities.types.ts
  src/types/profile-menu.types.ts
Labels: 🐛버그 수정 (Bug), ✨기능 추가 (Feature), 🔨 리팩토링 (Refactor)

#185 [Fix] 닉네임 및 내정보 유효성 수정
  src/app/account/components/forms/InitialForm.tsx
  src/app/account/components/forms/LoginForm.tsx
  src/app/account/components/forms/SignUpForm.tsx
  src/app/layout.tsx
  src/app/profile/my-info/page.tsx
  src/components/common/buttons/CheckBox.tsx
  src/components/common/modals/AuthModal.tsx
  src/providers/ModalProvider.tsx
  src/types/form.types.ts
  src/types/input.types.ts
Labels: 🐛버그 수정 (Bug)

#186 [Feat] Middleware
  src/app/_components/RecommendList.tsx
  src/middleware.ts
Labels: ✨기능 추가 (Feature)

#182 [Feat] 캘린더 컴포넌트 구현, 태블릿과 데스크톱 반응형 구현
  public/assets/icons/calendar/ico-carendar-arrow-left.svg
  public/assets/icons/calendar/ico-carendar-arrow-right.svg
  src/app/activities/[id]/components/ExperienceResponsiveLayout.tsx
  src/app/activities/[id]/components/experience/ExperienceImageViewer.tsx
  src/app/activities/[id]/components/experience/ExperienceLocationMap.tsx
  src/app/activities/[id]/components/experience/ExperienceSummarySection.tsx
  src/app/activities/[id]/components/reservation/ReservationBox.tsx
  src/app/activities/[id]/components/reservation/ReservationMobileFooter.tsx
  src/app/activities/[id]/components/reservation/ScheduleModal.tsx
  src/app/activities/[id]/components/reservation/ScheduleSidebar.tsx
  src/app/activities/[id]/components/reservation/ScheduleTimeItem.tsx
  src/app/activities/[id]/components/reservation/ScheduleTimeList.tsx
  src/app/activities/[id]/components/review/ReviewCard.tsx
  src/app/activities/[id]/components/review/ReviewListModal.tsx
  src/app/activities/[id]/components/review/ReviewSection.tsx
  src/app/activities/[id]/data/dummySchedule.ts
  src/app/activities/[id]/page.tsx
  src/components/common/calendar/CalendarArrowButton.tsx
  src/components/common/calendar/ReservationCalendarPicker.tsx
  src/components/common/icons/CalendarArrowLeftIcon.tsx
  src/components/common/icons/CalendarArrowRightIcon.tsx
  src/hooks/useFollowScrollPosition.ts
  src/styles/globals.css
  src/styles/reservation-calendar-picker.css
Labels: ✨기능 추가 (Feature)

#187 [Feat] 삭제 기능 구현
  src/app/profile/my-activities/[id]/edit/page.tsx
  src/app/profile/my-activities/components/activity-management/ManagementCard.tsx
  src/app/profile/my-activities/components/activity-management/ManagementDropdown.tsx
  src/hooks/useDeleteActivity.ts
Labels: ✨기능 추가 (Feature)

#195 [Feat] 체험 상세 부분 API 연결
  src/app/activities/[id]/components/ExperienceDetailClient.tsx
  src/app/activities/[id]/components/ExperienceResponsiveLayout.tsx
  src/app/activities/[id]/components/common/ExperienceDetailSkeleton.tsx
  src/app/activities/[id]/components/experience/ExperienceImageViewer.tsx
  src/app/activities/[id]/components/experience/ExperienceLocationMap.tsx
  src/app/activities/[id]/components/reservation/ReservationBox.tsx
  src/app/activities/[id]/components/reservation/ReservationMobileFooter.tsx
  src/app/activities/[id]/components/reservation/ScheduleModal.tsx
  src/app/activities/[id]/components/reservation/ScheduleSidebar.tsx
  src/app/activities/[id]/components/reservation/ScheduleTimeItem.tsx
  src/app/activities/[id]/components/reservation/ScheduleTimeList.tsx
  src/app/activities/[id]/components/review/ReviewListModal.tsx
  src/app/activities/[id]/components/review/ReviewSummary.tsx
  src/app/activities/[id]/data/dummyReviews.ts
  src/app/activities/[id]/data/dummySchedule.ts
  src/app/activities/[id]/page.tsx
  src/hooks/activities/useActivityDetail.ts
  src/hooks/activities/useReviews.ts
  src/hooks/activities/useSchedule.ts
  src/hooks/useInfiniteReviews.ts
  src/styles/reservation-calendar-picker.css
  src/types/activity.types.ts
  src/types/schedule.types.ts
Labels: 🐛버그 수정 (Bug), ✨기능 추가 (Feature)

#184 [Feat] 체험 찜하기 기능 및 찜목록 페이지
  src/app/_components/ActivityCard.tsx
  src/app/_components/ActivityList.tsx
  src/app/_components/UserInitializer.tsx
  src/app/client-layout.tsx
  src/app/profile/favorites/components/FavoriteCard.tsx
  src/app/profile/favorites/components/FavoritesList.tsx
  src/app/profile/favorites/components/NotFoundActivities.tsx
  src/app/profile/favorites/page.tsx
  src/components/common/buttons/LinkButton.tsx
  src/hooks/auth/useAuth.ts
  src/lib/fetch/fetchFromClient.ts
  src/services/authApi.ts
  src/store/favoritesStore.ts
Labels: 🐛버그 수정 (Bug), ✨기능 추가 (Feature), 💄 스타일 (Style), 🔨 리팩토링 (Refactor)

#193 [Fix] 예약 내역 페이지 클라이언트 컴포넌트 분리
  src/app/profile/reservations/components/ReservationsMain.tsx
  src/app/profile/reservations/page.tsx
Labels: 🐛버그 수정 (Bug), 🔨 리팩토링 (Refactor)

#204 [Feat] 알림 기능 및 빌드 에러 수정
  next.config.ts
  src/app/_components/ActivityList.tsx
  src/app/_components/NotificationModal.tsx
  src/app/client-layout.tsx
  src/app/page.tsx
  src/app/profile/notifications/components/.gitkeep
  src/app/profile/notifications/page.tsx
  src/app/test/button/page.tsx
  src/app/test/dropdown/menu/page.tsx
  src/app/test/dropdown/page.tsx
  src/app/test/gnb/page.tsx
  src/app/test/input/page.tsx
  src/app/test/modal/page.tsx
  src/app/test/route/activities/CreateActivityTest.tsx
  src/app/test/route/activities/page.tsx
  src/app/test/route/auth/page.tsx
  src/app/test/route/my-activities/MyActivityTest.tsx
  src/app/test/route/my-activities/page.tsx
  src/app/test/route/my-notifications/NotificationDeleteTest.tsx
  src/app/test/route/my-notifications/page.tsx
  src/app/test/route/my-reservations/page.tsx
  src/app/test/route/users/page.tsx
  src/app/test/share/page.tsx
  src/app/test/toast/page.tsx
  src/components/layout/navbar/components/CategorySection.tsx
  src/components/layout/navbar/components/PlaceFilter.tsx
  src/components/layout/navbar/desktop/DesktopFilterSection.tsx
  src/components/layout/navbar/desktop/DesktopGNB.tsx
  src/components/layout/navbar/mobile/BNB.tsx
  src/hooks/useBreakpoint.ts
  src/hooks/useNotifications.ts
  src/lib/formatRelativeTime.ts
  src/types/notification.types.ts
Labels: 🐛버그 수정 (Bug), ✨기능 추가 (Feature), 🔧 설정 변경 (Chore)

#207 [Fix] 로그인 path 수정
  src/lib/fetch/fetchFromClient.ts
  src/lib/fetch/fetchFromServer.ts
Labels: 🐛버그 수정 (Bug)

#212 [Fix] 프로필 API path 수정
  src/services/userService.ts
Labels: 🐛버그 수정 (Bug)

#211 [Feat] 검색 시 지도 기능 및 GNB로 인한 layout 간격 조정
  src/app/_components/ActivityList.tsx
  src/app/_components/PopularActivitiesBanner.tsx
  src/app/_components/SearchResultMap.tsx
  src/app/_components/SearchResultsWithMap.tsx
  src/app/client-layout.tsx
  src/app/page.tsx
  src/components/layout/navbar/components/Category.tsx
  src/components/layout/navbar/components/PlaceFilter.tsx
  src/components/layout/navbar/desktop/DesktopCategorySection.tsx
  src/components/layout/navbar/desktop/DesktopGNB.tsx
Labels: 🐛버그 수정 (Bug), ✨기능 추가 (Feature), 💄 스타일 (Style)

#217 [Fix] 체험 상세 페이지 디자인 변경
  package-lock.json
  package.json
  public/assets/badge/Badge.glb
  public/assets/icons/badge/curious.svg
  public/assets/icons/badge/expert.svg
  public/assets/icons/badge/god.svg
  public/assets/icons/badge/kitten.svg
  public/assets/icons/badge/professor.svg
  public/assets/icons/test/img-main.jpg
  public/assets/icons/test/img-sub1.jpg
  public/assets/icons/test/img-sub2.jpg
  public/assets/icons/test/img-sub3.jpg
  public/assets/icons/test/user1.jpg
  public/assets/icons/test/user2.jpg
  public/assets/icons/test/user3.jpg
  public/assets/icons/test/user4.jpg
  public/assets/icons/test/user5.jpg
  public/assets/icons/test/user6.jpg
  src/app/activities/[id]/components/ExperienceResponsiveLayout.tsx
  src/app/activities/[id]/components/common/ExperienceDetailSkeleton.tsx
  src/app/activities/[id]/components/experience/ExperienceImageViewer.tsx
  src/app/activities/[id]/components/reservation/ReservationMobileFooter.tsx
  src/app/activities/[id]/components/reservation/ScheduleModal.tsx
  src/app/activities/[id]/components/reservation/ScheduleTimeItem.tsx
  src/app/activities/[id]/components/reservation/ScheduleTimeSlot.tsx
  src/app/test/badge/page.tsx
  src/components/common/badge/AllBadgeList.tsx
  src/components/common/badge/Badge.tsx
  src/components/common/badge/Badge3DViewer.tsx
  src/components/common/badge/BadgeEarnedModal.tsx
  src/components/common/badge/BadgeEarnedModalContent.tsx
  src/constants/badge.constans.ts
  src/hooks/useModal.tsx
  src/hooks/useMyBadge.ts
  src/store/useBadgeStore.ts
  src/styles/globals.css
  src/styles/reservation-calendar-picker.css
Labels: 💄 스타일 (Style)

#213 [Style/Feat] Modal + Favicon
  public/assets/icons/ico-fav.svg
  src/app/account/components/forms/LoginForm.tsx
  src/app/account/components/forms/SignUpForm.tsx
  src/components/common/buttons/VisibilityToggleButton.tsx
  src/components/common/modals/ConfirmModal.tsx
  src/components/common/modals/Modal.tsx
  src/types/input.types.ts
Labels: 💄 스타일 (Style)

#221 [Style] 스켈레톤 ui 구현
  src/app/profile/my-activities/[id]/edit/page.tsx
  src/app/profile/my-activities/components/RegisterExperienceForm.tsx
  src/app/profile/my-activities/components/skeleton-ui/SkeletonRegisterForm.tsx
  src/app/profile/my-activities/register/page.tsx
  src/app/profile/my-info/page.tsx
  src/app/test/skeleton/page.tsx
Labels: 💄 스타일 (Style), ✅ 테스트 (Test)

#225 [Refactor] 불필요한 Toast 컴포넌트 제외
  src/components/common/modals/CreateReviewModal.tsx
  src/store/toastStore.ts
Labels: 🔨 리팩토링 (Refactor)

#223 [Feat] 통계 페이지 UI
  package-lock.json
  src/app/profile/analytics/monthly-pending-chart/MonthlyPendingChart.tsx
  src/app/profile/analytics/page.tsx
  src/app/profile/analytics/reservation-stats/ReservationLineChart.tsx
  src/app/profile/analytics/reservation-stats/SummaryCards.tsx
  src/app/profile/analytics/review-summary/MyActivitiesReviewList.tsx
  src/app/profile/analytics/review-summary/MyActivityReviewCard.tsx
  src/app/profile/analytics/review-summary/SkeletonReviewCard.tsx
Labels: ✨기능 추가 (Feature), 💄 스타일 (Style)

#226 [Fix] 체험 카드 버블링 수정
  package-lock.json
  src/app/layout.tsx
  src/app/profile/layout.tsx
  src/app/profile/my-activities/components/activity-management/ManagementCard.tsx
  src/app/profile/my-activities/components/activity-management/ManagementCards.tsx
  src/app/profile/my-info/page.tsx
  src/app/profile/reservations/components/ReservationsMain.tsx
  src/hooks/useDeleteActivity.ts
  src/hooks/useInfiniteActivities.ts
Labels: 💄 스타일 (Style), 🔨 리팩토링 (Refactor)

#228 [Refactor] 상세 페이지 SSR로 변경
  src/app/activities/[id]/components/ExperienceDetailClient.tsx
  src/app/activities/[id]/components/ExperienceResponsiveLayout.tsx
  src/app/activities/[id]/components/common/ActivityDropdown.tsx
  src/app/activities/[id]/components/common/ExperienceDetailSkeleton.tsx
  src/app/activities/[id]/components/experience/ExperienceSummarySection.tsx
  src/app/activities/[id]/components/reservation/ScheduleTimeItem.tsx
  src/app/activities/[id]/components/reservation/ScheduleTimeSlot.tsx
  src/app/activities/[id]/components/review/ReviewListModal.tsx
  src/app/activities/[id]/page.tsx
  src/app/profile/my-activities/components/register-calendar/RegisterCalendar.tsx
  src/lib/fetch/fetchFromServer.ts
  src/utils/response-helpers.ts
Labels: 🔨 리팩토링 (Refactor)

#230 [Fix] 예약 현황 캘린더 fine-tune(캘린더 tile 너비 줄여듦 현상 & 캘린더 쿼리 무효화)
  src/app/profile/my-reservations/components/MyReservationsModalCard.tsx
  src/app/profile/my-reservations/components/ReservationCalendar.tsx
  src/hooks/useUpdateReservation.ts
  src/styles/reservation-calendar.css
Labels: 🐛버그 수정 (Bug), 💄 스타일 (Style)

#232 [Style] 체험 상세페이지 다크모드
  public/assets/icons/ico-share.svg
  src/app/activities/[id]/components/ExperienceResponsiveLayout.tsx
  src/app/activities/[id]/components/common/SectionTitle.tsx
  src/app/activities/[id]/components/experience/ExperienceDescription.tsx
  src/app/activities/[id]/components/experience/ExperienceImageViewer.tsx
  src/app/activities/[id]/components/experience/ExperienceSummarySection.tsx
  src/app/activities/[id]/components/reservation/ReservationBox.tsx
  src/app/activities/[id]/components/reservation/ReservationMobileFooter.tsx
  src/app/activities/[id]/components/reservation/ScheduleTimeItem.tsx
  src/app/activities/[id]/components/review/ReviewCard.tsx
  src/app/activities/[id]/components/review/ReviewListModal.tsx
  src/app/activities/[id]/components/review/ReviewSection.tsx
  src/app/activities/[id]/components/review/ReviewSummary.tsx
  src/components/common/calendar/ReservationCalendarPicker.tsx
Labels: 💄 스타일 (Style)

#233 [Style] 예약 내역 다크모드
  src/components/common/buttons/BaseButton.tsx
  src/components/common/modals/CreateReviewModal.tsx
  src/constants/my-reservation-status.ts
Labels: 💄 스타일 (Style)

#236 [Fix] Fine Tune - 리다이랙트 에러, 유효하지 않은 시간 입력
  src/app/profile/my-activities/components/RegisterExperienceForm.tsx
  src/app/profile/my-activities/components/register-calendar/DateTimePicker.tsx
  src/app/profile/my-activities/components/register-calendar/RegisterCalendarItem.tsx
  src/app/profile/page.tsx
  src/utils/my-activities-time.ts
Labels: 🐛버그 수정 (Bug), ✨기능 추가 (Feature), 💄 스타일 (Style), 🔨 리팩토링 (Refactor), 📚 문서 (Docs)

#238 [Fix] 찜목록 새로고침 수정
  src/app/profile/favorites/components/FavoritesList.tsx
Labels: 🐛버그 수정 (Bug)

#235 [Fix] 수정 시 이미지 복사
  src/app/profile/my-activities/[id]/edit/page.tsx
  src/app/profile/my-activities/components/RegisterExperienceForm.tsx
  src/app/profile/my-activities/components/register-form/PostAddress.tsx
  src/app/profile/my-activities/components/register-form/UploadImg.tsx
  src/app/profile/my-activities/components/register-form/UploadImgList.tsx
  src/app/profile/my-activities/register/page.tsx
  src/app/profile/reservations/components/ReservationsMain.tsx
  src/components/common/dropdowns/DropdownMenu.tsx
  src/components/common/inputs/Textarea.tsx
  src/hooks/activities/useActivityDetail.ts
  src/utils/my-activities.ts
Labels: 🐛버그 수정 (Bug), 🔨 리팩토링 (Refactor)

#239 [Feat] fine-tune 반영
  src/app/_components/SearchResultsWithMap.tsx
  src/components/layout/navbar/components/SubPageGNB.tsx
  src/components/layout/navbar/desktop/DesktopGNB.tsx
  src/components/layout/navbar/mobile/BNB.tsx
  src/components/layout/navbar/mobile/MobileSearchFilters.tsx
Labels: 🐛버그 수정 (Bug), ✨기능 추가 (Feature)

#237 [Fix] 이미 예약한 시간 선택하지 못 하도록 ui 수정
  package-lock.json
  src/app/activities/[id]/components/reservation/ScheduleList.tsx
  src/app/activities/[id]/components/reservation/ScheduleModal.tsx
  src/app/activities/[id]/components/reservation/ScheduleTimeItem.tsx
  src/app/activities/[id]/components/reservation/ScheduleTimeList.tsx
  src/app/activities/[id]/components/reservation/ScheduleTimeSlot.tsx
  src/hooks/activities/useMyReservedScheduleIds.ts
Labels: 🐛버그 수정 (Bug), ✨기능 추가 (Feature)

#243 [Fix] 상세 페이지 디테일 수정
  src/app/activities/[id]/components/ExperienceResponsiveLayout.tsx
  src/app/activities/[id]/components/common/ActivityDropdown.tsx
  src/app/activities/[id]/components/experience/ExperienceImageViewer.tsx
  src/app/activities/[id]/components/reservation/ScheduleTimeItem.tsx
Labels: 🐛버그 수정 (Bug)

#249 [Fix] 캘린더 오늘 날짜의 label width 줄어듦 현상 해결
  src/app/profile/my-reservations/components/ReservationCalendar.tsx
  src/styles/reservation-calendar.css
Labels: 🐛버그 수정 (Bug), 💄 스타일 (Style)

#245 [Fix] 이미지 두번 클릭시 업로드
  src/app/profile/my-activities/components/register-form/UploadImgList.tsx
Labels: 🐛버그 수정 (Bug)

#248 [Style] achievements 페이지 다크모드
  src/app/profile/achievements/page.tsx
  src/components/common/badge/AllBadgeList.tsx
  src/components/common/badge/BadgeDetailModalContent.tsx
  src/components/common/badge/BadgeGLBViewer.tsx
Labels: 🐛버그 수정 (Bug), 💄 스타일 (Style)

#252 [Fix] 데스크탑 드롭다운 수정
  package-lock.json
  src/app/activities/[id]/components/ExperienceResponsiveLayout.tsx
  src/utils/my-activities-time 2.ts
Labels: 🐛버그 수정 (Bug)

#255 [Fix] 뱃지 획득 안 되는 이슈 해결
  src/hooks/achievements/useCompletedCategories.ts
Labels: 🐛버그 수정 (Bug)
